# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'liveroom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for liveroom
	pod 'Masonry', '~> 1.1.0'
    pod 'CocoaLumberjack', '~> 3.4.2'
    pod 'MJRefresh'
    pod 'Hyphenate', '~> 3.5.4'
end
